spring.application.name=erp00


server.port = 2222

erp_socketServer=ws:192.168.0.106:2222/chat

spring.datasource.url=jdbc:oracle:thin:@192.168.0.106:1521:xe
spring.datasource.username=erp00
spring.datasource.password=erp00
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
# reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

user.upload =  C:/javaexp01/sts/workspace/erp00_svn/src/main/webapp/z01_load
#           C:\a01_javaexp\sts\workspace\erp00\src\main\resources\static\upload
spring.servlet.multipart.max-file-size=300MB  
spring.servlet.multipart.max-request-size=300MB  

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hainsol116@gmail.com
spring.mail.password=vlwblcdvoexaazcb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.transport.protocol=smtp




